{{- if .Values.caCertificates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enterprise-steam.fullname" . }}-ca-certificates
data:
  steam-ca-bundle.crt: {{ .Values.caCertificates }}
{{- end }}