{{- if not .Values.persistentVolume.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "enterprise-steam.fullname" . }}
  labels:
    {{- include "enterprise-steam.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.persistentVolume.annotations }}
    {{ toYaml . }}
  {{- end }}
  {{- if eq .Values.persistentVolume.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    {{- .Values.persistentVolume.accessModes | toYaml | nindent 4 }}
{{- if .Values.persistentVolume.storageClassName }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- end }}