{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enterprise-steam.serviceAccountName" . }}
  labels:
    {{- include "enterprise-steam.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
automountServiceAccountToken: false
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "enterprise-steam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise-steam.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "apps", "storage.k8s.io"]
    resources: ["namespaces", "pods", "pods/log", "deployments", "secrets", "services", "persistentvolumeclaims", "persistentvolumes", "events", "configmaps", "storageclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    {{- if .Values.serviceAccount.openshift }}
  - apiGroups: [ "security.openshift.io" ]
    resources: [ "securitycontextconstraints" ]
    {{- with .Values.serviceAccount.openshiftResourceNames }}
    resourceNames:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    verbs: [ "use" ]
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "enterprise-steam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise-steam.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "enterprise-steam.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "enterprise-steam.fullname" . }}
{{- end }}
{{- if and .Values.serviceAccount.create .Values.serviceAccount.allowClusterRolePrivileges }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "enterprise-steam.fullname" . }}
  labels:
    {{- include "enterprise-steam.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "storage.k8s.io"]
    resources: ["nodes", "namespaces", "storageclasses", "resourcequotas"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "enterprise-steam.fullname" . }}
  labels:
    {{- include "enterprise-steam.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "enterprise-steam.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "enterprise-steam.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}